### ISSUE TITLE
Some FraxBP Metapools have incorrect `metapool` property on `Pool` entity

### ISSUE THREAD

**Issue by bam4564** [curvefi/volume-subgraphs#18]
I'm running this query
```graphql
query MyQuery {
  pools(where: {coins_contains: ["0x3175df0976dfa876431c2e9ee6bc45b65d3473cc"]}) {
    metapool
    address
    name
  }
}
```
Against [this](https://api.thegraph.com/subgraphs/name/convex-community/volume-mainnet) subgraph.

Where the address `0x3175df0976dfa876431c2e9ee6bc45b65d3473cc` is the lp token crvFrax (for the Frax/Usdc pool). I'm doing some analytics on the metapools for this base pool. 

The (abbreviated) results from this query are as follows 
```json
{
  "data": {
    "pools": [
      ...
      {
        "metapool": true,
        "address": "0x04b727c7e246ca70d496ecf52e6b6280f3c8077d",
        "name": "Curve.fi Factory USD Metapool: apeUSDFRAXBP"
      },
      ...,
      {
        "metapool": false,
        "address": "0x13b876c26ad6d21cb87ae459eaf6d7a1b788a113",
        "name": "Curve.fi Factory Crypto Pool: BADGER/FRAXBP"
      },
      ...,
}
```
Since a metapool by definition consists of some asset paired with a lp token from another curve pool, I would think that the `metapool` property for both of these pools should be true. But this is not the case for he Badger/FraxBP pool. 

Badger/FraxBP curve: https://curve.fi/#/ethereum/pools/factory-crypto-101/deposit
ApeUSD/FraxBP curve: https://curve.fi/#/ethereum/pools/factory-v2-138/deposit
Badger/FraxBP etherscan: https://etherscan.io/address/0x13b876c26ad6d21cb87ae459eaf6d7a1b788a113
ApeUSD/FraxBP etherscan: https://etherscan.io/address/0x04b727c7e246ca70d496ecf52e6b6280f3c8077d

Is this the desired behavior or is this a bug?

**Comment by benber86** [comment]
A metapool is not just a pairing between an LP token and N other tokens, it also allows you to trade the tokens for the underlying assets of the LP token's pool. 

For instance the alUSD metapool is not just a 3CRV / alUSD pair, it allows you to trade alUSD for the underlying assets of the 3pool like USDT, DAI, USDC. The v2 pools you mention do not let you do that, it merely lets you trade BADGER for crvFrax. 

There is currently no option to deploy v2 metapools on mainnet although that may change in the future.

**Comment by bam4564** [comment]
Makes sense. So is it correct to think about metapools as a v1 pool type and factory pools as a v2 pool type? And if so, is there any documentation on the reasoning between this switch between v1 and v2?

**Comment by benber86** [comment]
> Makes sense. So is it correct to think about metapools as a v1 pool type and factory pools as a v2 pool type? And if so, is there any documentation on the reasoning between this switch between v1 and v2?

No, you can both have v1 plain pools and v1 metapools. Factory pools are just pools that are deployed with the factory contract as opposed to manually deployed implementations (which may have custom features). Most new pools are expected to be factory pool at this point. It's possible to have factory plain pools and factory metapools.

There are likewise non-factory v2 pools (like tricrypto) and factory v2 pools (most of the v2 pools). There are no v2 metapools on mainnet currently. It's not technically impossible to have v2 metapools but AFAIK the gas costs on mainnet would be too expensive to make it worthwhile.

For the main differences between v1 and v2, refer to the whitepapers:
v1: https://curve.fi/files/stableswap-paper.pdf
v2: https://classic.curve.fi/files/crypto-pools-paper.pdf

**Comment by bam4564** [comment]
Thanks for the info. I'll close the issue since this is a non-issue.
